playstation_achievements_error = Trofeje PlayStation se nepodařilo aktualizovat.
playstation_auth_failed = Ověření se nezdařilo. Podrobnosti najdete v protokolu Playnite.
playstation_auth_not_checked = Neověřeno
playstation_auth_step_browser = 1. Přihlaste se k PlayStation v běžném prohlížeči a zvolte „Důvěřovat tomuto prohlížeči“.
playstation_auth_step_open = 2. Otevřete
playstation_auth_step_open_suffix = v tomto prohlížeči.
playstation_auth_step_paste = 3. Níže vložte buď hodnotu NPSSO, nebo celou odpověď { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Vypršel časový limit ověření.
playstation_authentication_label = Ověření
playstation_invalid_npsso_title = Neplatné NPSSO
playstation_legacy_platforms_description = Tyto systémy uvádí pouze API trofejí, takže se hry pro ně importují z vašeho seznamu trofejí. Vypnutí platformy tyto hry z importu vyloučí.
playstation_legacy_platforms_label = Starší platformy
playstation_library_label = Knihovna PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Zobrazit nebo skrýt NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Použít samostatný zdroj „PlayStation Plus“ pro hry, které nevlastníte natrvalo
playstation_plus_tag_checkbox = Označit hry zahrnuté v PlayStation Plus
playstation_region_description = Vyžádá lokalizované názvy a popisy trofejí. Nejbližší aktualizace trofejí po změně stáhne trofeje PlayStation znovu a může chvíli trvat. Pokud trofej překlad nemá, PlayStation použije jiný jazyk.
playstation_region_label = Jazyk trofejí
playstation_settings_save_failed = Nastavení PlayStation se nepodařilo uložit. Ověřte, že do složky uživatelských dat Playnite lze zapisovat.
playstation_trophy_only_checkbox = Importovat hry, které se objevují pouze v seznamu trofejí
playstation_trophy_only_description = Najde diskové hry, které PlayStation nikdy nehlásí jako nákup. Ke stávajícím hrám je lze přiřadit jen podle názvu, takže titul s odlišným názvem se může importovat podruhé. Objevit se mohou i doplňky a rozšíření.
playstation_trophy_only_label = Hry pouze v seznamu trofejí
