playstation_achievements_error = Impossibile aggiornare i trofei PlayStation.
playstation_auth_failed = Verifica dell’autenticazione non riuscita. Consulta il registro di Playnite per i dettagli.
playstation_auth_not_checked = Non verificato
playstation_auth_step_browser = 1. Accedi a PlayStation nel tuo browser abituale e scegli «Considera attendibile questo browser».
playstation_auth_step_open = 2. Apri
playstation_auth_step_open_suffix = in quel browser.
playstation_auth_step_paste = 3. Incolla qui sotto il valore NPSSO oppure la risposta completa { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Verifica dell’autenticazione scaduta.
playstation_authentication_label = Autenticazione
playstation_invalid_npsso_title = NPSSO non valido
playstation_legacy_platforms_description = Questi sistemi compaiono solo nell’API dei trofei, quindi i relativi giochi vengono importati dal tuo elenco trofei. Disattivare una piattaforma esclude quei giochi dall’importazione.
playstation_legacy_platforms_label = Piattaforme precedenti
playstation_library_label = Libreria PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Mostra o nascondi il NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Usa una fonte «PlayStation Plus» separata per i giochi che non possiedi definitivamente
playstation_plus_tag_checkbox = Contrassegna i giochi inclusi in PlayStation Plus
playstation_region_description = Richiede nomi e descrizioni dei trofei localizzati. Il primo aggiornamento dei trofei dopo la modifica riscarica i trofei PlayStation e può richiedere tempo. PlayStation può ripiegare su un’altra lingua se un trofeo non è tradotto.
playstation_region_label = Lingua dei trofei
playstation_settings_save_failed = Impossibile salvare le impostazioni PlayStation. Verifica che la cartella dei dati utente di Playnite sia scrivibile.
playstation_trophy_only_checkbox = Importa i giochi che compaiono solo nel tuo elenco trofei
playstation_trophy_only_description = Individua i giochi su disco che PlayStation non segnala mai come acquisto. Possono essere associati ai giochi già presenti solo tramite il nome, quindi un titolo con un nome diverso potrebbe essere importato una seconda volta. Possono comparire anche contenuti aggiuntivi ed espansioni.
playstation_trophy_only_label = Giochi presenti solo nei trofei
