playstation_achievements_error = De PlayStation-trofeeën konden niet worden bijgewerkt.
playstation_auth_failed = Authenticatiecontrole mislukt. Zie het Playnite-logboek voor details.
playstation_auth_not_checked = Niet gecontroleerd
playstation_auth_step_browser = 1. Meld je in je gewone browser aan bij PlayStation en kies ‘Deze browser vertrouwen’.
playstation_auth_step_open = 2. Open
playstation_auth_step_open_suffix = in die browser.
playstation_auth_step_paste = 3. Plak hieronder de NPSSO-waarde of het volledige antwoord { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Time-out bij de authenticatiecontrole.
playstation_authentication_label = Authenticatie
playstation_invalid_npsso_title = Ongeldige NPSSO
playstation_legacy_platforms_description = Deze systemen staan alleen in de trofee-API, dus spellen daarvoor worden uit je trofeeënlijst geïmporteerd. Een uitgeschakeld platform sluit die spellen uit van de import.
playstation_legacy_platforms_label = Oudere platforms
playstation_library_label = PlayStation-bibliotheek
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = NPSSO tonen of verbergen
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Een aparte bron ‘PlayStation Plus’ gebruiken voor spellen die je niet blijvend bezit
playstation_plus_tag_checkbox = Spellen labelen die bij PlayStation Plus zitten
playstation_region_description = Vraagt gelokaliseerde trofeenamen en -beschrijvingen op. De eerstvolgende trofee-update na een wijziging haalt de PlayStation-trofeeën opnieuw op en kan even duren. PlayStation valt terug op een andere taal als een trofee geen vertaling heeft.
playstation_region_label = Trofeetaal
playstation_settings_save_failed = De PlayStation-instellingen konden niet worden opgeslagen. Controleer of de map met Playnite-gebruikersgegevens beschrijfbaar is.
playstation_trophy_only_checkbox = Spellen importeren die alleen in je trofeeënlijst staan
playstation_trophy_only_description = Vindt schijfspellen die PlayStation nooit als aankoop meldt. Ze kunnen alleen op naam aan je bestaande spellen worden gekoppeld, dus een titel met een afwijkende naam kan een tweede keer worden geïmporteerd. Ook aanvullende content en uitbreidingen kunnen verschijnen.
playstation_trophy_only_label = Spellen alleen in trofeeënlijst
