playstation_achievements_error = Nie udało się zaktualizować trofeów PlayStation.
playstation_auth_failed = Sprawdzanie uwierzytelnienia nie powiodło się. Szczegóły znajdziesz w dzienniku Playnite.
playstation_auth_not_checked = Niesprawdzone
playstation_auth_step_browser = 1. Zaloguj się do PlayStation w zwykłej przeglądarce i wybierz „Ufaj tej przeglądarce”.
playstation_auth_step_open = 2. Otwórz
playstation_auth_step_open_suffix = w tej przeglądarce.
playstation_auth_step_paste = 3. Wklej poniżej wartość NPSSO albo pełną odpowiedź { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Przekroczono czas sprawdzania uwierzytelnienia.
playstation_authentication_label = Uwierzytelnianie
playstation_invalid_npsso_title = Nieprawidłowe NPSSO
playstation_legacy_platforms_description = Te systemy są wykazywane wyłącznie przez API trofeów, więc gry na nie są importowane z listy trofeów. Wyłączenie platformy pomija te gry podczas importu.
playstation_legacy_platforms_label = Starsze platformy
playstation_library_label = Biblioteka PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Pokaż lub ukryj NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Używaj osobnego źródła „PlayStation Plus” dla gier, których nie posiadasz na własność
playstation_plus_tag_checkbox = Oznaczaj gry dostępne w PlayStation Plus
playstation_region_description = Pobiera nazwy i opisy trofeów w wybranym języku. Pierwsza aktualizacja trofeów po zmianie pobiera trofea PlayStation ponownie i może chwilę potrwać. Gdy trofeum nie ma tłumaczenia, PlayStation użyje innego języka.
playstation_region_label = Język trofeów
playstation_settings_save_failed = Nie udało się zapisać ustawień PlayStation. Sprawdź, czy folder danych użytkownika Playnite jest zapisywalny.
playstation_trophy_only_checkbox = Importuj gry występujące wyłącznie na liście trofeów
playstation_trophy_only_description = Znajduje gry pudełkowe, których PlayStation nigdy nie zgłasza jako zakupu. Można je dopasować do posiadanych gier tylko po nazwie, więc tytuł o innej nazwie może zostać zaimportowany po raz drugi. Mogą pojawić się także dodatki i rozszerzenia.
playstation_trophy_only_label = Gry tylko z listy trofeów
