playstation_achievements_error = Não foi possível atualizar os troféus da PlayStation.
playstation_auth_failed = Falha na verificação de autenticação. Consulte o log do Playnite para mais detalhes.
playstation_auth_not_checked = Não verificado
playstation_auth_step_browser = 1. Entre na PlayStation pelo seu navegador normal e escolha “Confiar neste navegador”.
playstation_auth_step_open = 2. Abra
playstation_auth_step_open_suffix = nesse navegador.
playstation_auth_step_paste = 3. Cole abaixo o valor NPSSO ou a resposta completa { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Tempo esgotado na verificação de autenticação.
playstation_authentication_label = Autenticação
playstation_invalid_npsso_title = NPSSO inválido
playstation_legacy_platforms_description = Esses sistemas só aparecem na API de troféus, portanto os jogos deles são importados da sua lista de troféus. Desativar uma plataforma exclui esses jogos da importação.
playstation_legacy_platforms_label = Plataformas antigas
playstation_library_label = Biblioteca da PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Mostrar ou ocultar o NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Usar uma fonte “PlayStation Plus” separada para jogos que você não possui definitivamente
playstation_plus_tag_checkbox = Marcar jogos incluídos na PlayStation Plus
playstation_region_description = Solicita nomes e descrições de troféus localizados. A próxima atualização de troféus após a alteração baixa os troféus da PlayStation novamente e pode demorar. A PlayStation pode recorrer a outro idioma quando um troféu não tem tradução.
playstation_region_label = Idioma dos troféus
playstation_settings_save_failed = Não foi possível salvar as configurações da PlayStation. Verifique se a pasta de dados de usuário do Playnite permite gravação.
playstation_trophy_only_checkbox = Importar jogos que aparecem apenas na sua lista de troféus
playstation_trophy_only_description = Encontra jogos em disco que a PlayStation nunca informa como compra. Eles só podem ser associados aos jogos que você já tem pelo nome, então um título com nome diferente pode ser importado uma segunda vez. Conteúdos adicionais e expansões também podem aparecer.
playstation_trophy_only_label = Jogos apenas na lista de troféus
