playstation_achievements_error = Die PlayStation-Errungenschaften konnten nicht aktualisiert werden.
playstation_auth_failed = Authentifizierungsprüfung fehlgeschlagen. Weitere Angaben stehen im Playnite-Protokoll.
playstation_auth_not_checked = Nicht geprüft
playstation_auth_step_browser = 1. Melde dich in deinem normalen Browser bei PlayStation an und wähle „Diesem Browser vertrauen“.
playstation_auth_step_open = 2. Öffne
playstation_auth_step_open_suffix = in diesem Browser.
playstation_auth_step_paste = 3. Füge unten entweder den NPSSO-Wert oder die vollständige Antwort { "{" }"npsso":"…"{ "}" } ein.
playstation_auth_timed_out = Zeitüberschreitung bei der Authentifizierungsprüfung.
playstation_authentication_label = Authentifizierung
playstation_invalid_npsso_title = Ungültiges NPSSO
playstation_legacy_platforms_description = Diese Systeme werden nur von der Trophäen-API aufgeführt, daher werden Spiele dafür aus deiner Trophäenliste importiert. Eine deaktivierte Plattform schließt diese Spiele vom Import aus.
playstation_legacy_platforms_label = Ältere Plattformen
playstation_library_label = PlayStation-Bibliothek
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = NPSSO anzeigen oder verbergen
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Eine separate Quelle „PlayStation Plus“ für Spiele verwenden, die dir nicht dauerhaft gehören
playstation_plus_tag_checkbox = Spiele kennzeichnen, die in PlayStation Plus enthalten sind
playstation_region_description = Fordert lokalisierte Trophäennamen und -beschreibungen an. Die nächste Trophäenaktualisierung nach einer Änderung lädt die PlayStation-Trophäen neu und kann eine Weile dauern. PlayStation greift auf eine andere Sprache zurück, wenn für eine Trophäe keine Übersetzung vorliegt.
playstation_region_label = Trophäensprache
playstation_settings_save_failed = Die PlayStation-Einstellungen konnten nicht gespeichert werden. Prüfe, ob der Playnite-Benutzerdatenordner beschreibbar ist.
playstation_trophy_only_checkbox = Spiele importieren, die nur in der Trophäenliste erscheinen
playstation_trophy_only_description = Findet Disc-Spiele, die PlayStation nie als Kauf meldet. Sie lassen sich nur über den Namen mit bereits vorhandenen Spielen abgleichen, daher kann ein Titel mit abweichendem Namen ein zweites Mal importiert werden. Auch Zusatzinhalte und Erweiterungen können auftauchen.
playstation_trophy_only_label = Nur in Trophäenliste enthaltene Spiele
