playstation_achievements_error = Impossible de mettre à jour les trophées PlayStation.
playstation_auth_failed = Échec de la vérification de l’authentification. Consultez le journal de Playnite pour plus de détails.
playstation_auth_not_checked = Non vérifié
playstation_auth_step_browser = 1. Connectez-vous à PlayStation dans votre navigateur habituel et choisissez « Faire confiance à ce navigateur ».
playstation_auth_step_open = 2. Ouvrez
playstation_auth_step_open_suffix = dans ce navigateur.
playstation_auth_step_paste = 3. Collez ci-dessous soit la valeur NPSSO, soit la réponse complète { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Délai dépassé lors de la vérification de l’authentification.
playstation_authentication_label = Authentification
playstation_invalid_npsso_title = NPSSO non valide
playstation_legacy_platforms_description = Ces systèmes ne sont listés que par l’API des trophées ; les jeux correspondants sont donc importés depuis votre liste de trophées. Désactiver une plateforme exclut ces jeux de l’import.
playstation_legacy_platforms_label = Anciennes plateformes
playstation_library_label = Bibliothèque PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Afficher ou masquer le NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Utiliser une source « PlayStation Plus » distincte pour les jeux que vous ne possédez pas définitivement
playstation_plus_tag_checkbox = Marquer les jeux inclus dans PlayStation Plus
playstation_region_description = Demande des noms et descriptions de trophées localisés. La prochaine mise à jour des trophées après un changement recharge les trophées PlayStation et peut prendre un certain temps. PlayStation peut utiliser une autre langue si un trophée n’est pas traduit.
playstation_region_label = Langue des trophées
playstation_settings_save_failed = Impossible d’enregistrer les paramètres PlayStation. Vérifiez que le dossier de données utilisateur de Playnite est accessible en écriture.
playstation_trophy_only_checkbox = Importer les jeux qui apparaissent uniquement dans votre liste de trophées
playstation_trophy_only_description = Détecte les jeux sur disque que PlayStation ne signale jamais comme achat. Ils ne peuvent être rapprochés de vos jeux existants que par leur nom : un titre dont le nom diffère peut donc être importé une seconde fois. Des contenus additionnels et extensions peuvent également apparaître.
playstation_trophy_only_label = Jeux présents uniquement dans les trophées
