playstation_library_label = PlayStation Library
playstation_authentication_label = Authentication
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Show or hide the NPSSO
playstation_region_label = Trophy language
playstation_region_description = Requests localized trophy names and descriptions. The next trophies update after changing it refreshes PlayStation trophies and may take a while. PlayStation may fall back when a trophy has no translation in the selected language.
playstation_legacy_platforms_label = Legacy platforms
playstation_legacy_platforms_description = These systems are only listed by the trophy API, so games for them are imported from your trophy list. Disabling a platform excludes those games from the import.
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_trophy_only_label = Trophy-only games
playstation_trophy_only_checkbox = Import games that appear only in your trophy list
playstation_trophy_only_description = Finds disc games that PlayStation never reports as a purchase. These can only be matched to games you already have by name, so a title whose names differ may be imported a second time. Add-ons and expansions may also appear.
playstation_plus_label = PlayStation Plus
playstation_plus_tag_checkbox = Tag games included with PlayStation Plus
playstation_plus_source_checkbox = Use a separate ‘PlayStation Plus’ source for games you do not own outright
playstation_settings_save_failed = PlayStation settings could not be saved. Check that the Playnite user data folder is writable.
playstation_achievements_error = PlayStation achievements could not be updated.
playstation_auth_step_browser = 1. Sign in to PlayStation in your normal browser and choose ‘Trust this Browser’.
playstation_auth_step_open = 2. Open
playstation_auth_step_open_suffix = in that browser.
playstation_auth_step_paste = 3. Paste either its NPSSO value or the complete { "{" }"npsso":"…"{ "}" } response below.
playstation_auth_not_checked = Not checked
playstation_auth_timed_out = Authentication check timed out.
playstation_auth_failed = Authentication check failed. See the Playnite log for details.
playstation_invalid_npsso_title = Invalid NPSSO

