playstation_achievements_error = No se pudieron actualizar los trofeos de PlayStation.
playstation_auth_failed = Error al comprobar la autenticación. Consulta el registro de Playnite para más detalles.
playstation_auth_not_checked = Sin comprobar
playstation_auth_step_browser = 1. Inicia sesión en PlayStation en tu navegador habitual y elige «Confiar en este navegador».
playstation_auth_step_open = 2. Abre
playstation_auth_step_open_suffix = en ese navegador.
playstation_auth_step_paste = 3. Pega abajo el valor NPSSO o la respuesta completa { "{" }"npsso":"…"{ "}" }.
playstation_auth_timed_out = Se agotó el tiempo de la comprobación de autenticación.
playstation_authentication_label = Autenticación
playstation_invalid_npsso_title = NPSSO no válido
playstation_legacy_platforms_description = Estos sistemas solo aparecen en la API de trofeos, por lo que sus juegos se importan desde tu lista de trofeos. Desactivar una plataforma excluye esos juegos de la importación.
playstation_legacy_platforms_label = Plataformas antiguas
playstation_library_label = Biblioteca de PlayStation
playstation_npsso_label = NPSSO
playstation_npsso_toggle_tooltip = Mostrar u ocultar el NPSSO
playstation_platform_ps3 = PlayStation 3
playstation_platform_psp = PlayStation Portable
playstation_platform_psvita = PlayStation Vita
playstation_plus_label = PlayStation Plus
playstation_plus_source_checkbox = Usar una fuente «PlayStation Plus» aparte para los juegos que no posees de forma permanente
playstation_plus_tag_checkbox = Etiquetar los juegos incluidos en PlayStation Plus
playstation_region_description = Solicita nombres y descripciones de trofeos localizados. La siguiente actualización de trofeos tras el cambio vuelve a descargar los trofeos de PlayStation y puede tardar. PlayStation puede recurrir a otro idioma si un trofeo no está traducido.
playstation_region_label = Idioma de los trofeos
playstation_settings_save_failed = No se pudieron guardar los ajustes de PlayStation. Comprueba que la carpeta de datos de usuario de Playnite permita escritura.
playstation_trophy_only_checkbox = Importar juegos que solo aparecen en tu lista de trofeos
playstation_trophy_only_description = Encuentra juegos en disco que PlayStation nunca informa como compra. Solo pueden asociarse por nombre con los juegos que ya tienes, así que un título cuyo nombre difiera podría importarse por segunda vez. También pueden aparecer contenidos adicionales y expansiones.
playstation_trophy_only_label = Juegos solo en la lista de trofeos
