AddonId: PlayStationLibrary_Builtin
Packages:
  - Version: 2.10
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.10/PlayStationLibrary_Builtin_2_10.pext
    Changelog:
      - Improved code for name cleanup
  - Version: 2.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-08
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.9/PlayStationLibrary_Builtin_2_9.pext
    Changelog:
      - Improved platform name handling
  - Version: 2.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-07
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.8/PlayStationLibrary_Builtin_2_8.pext
    Changelog:
      - Fixed cookie removal for reauthentication
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-05
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.7/PlayStationLibrary_Builtin_2_7.pext
    Changelog:
      - Improved authentication refresh handling
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-05
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.6/PlayStationLibrary_Builtin_2_6.pext
    Changelog:
      - Added playtime and last activity tracking
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-05
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.5/PlayStationLibrary_Builtin_2_5.pext
    Changelog:
      - Further improved authentication handling for mobile APIs
      - Added data migration from the old plugin
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-04
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.4/PlayStationLibrary_Builtin_2_4.pext
    Changelog:
      - Improved authentication handling for mobile APIs
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-04
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.3/PlayStationLibrary_Builtin_2_3.pext
    Changelog:
      - Added mobile API for game importing use
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-04
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.2/PlayStationLibrary_Builtin_2_2.pext
    Changelog:
      - Improved game importing
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-03
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.1/PlayStationLibrary_Builtin_2_1.pext
    Changelog:
      - Added a toggle to control image metadata downloading from PSN
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-02
    PackageUrl: https://github.com/XenorPLxx/playnite-library-psn/releases/download/2.0/PlayStationLibrary_Builtin_2_0.pext
    Changelog:
      - Playnite 9 support
      - Switched to the new API for authentication
      - Switched to the new API for game retrieval (all digital games owned and last 100 games played)
      - Changed Game Id (incompatible with previous versions of the extension, so it will cause duplicates if you used previous version)
      - Some non-digital games that weren't played recently might still be missing from the list
